name: PWA CI/CD Workflow

# Disparadores para el workflow
on:
  push:
    branches:
      - '*'    # Ejecutar las pruebas en cualquier rama en cada push
  pull_request:
    branches:
      - main   # Ejecutar las pruebas antes de fusionar a master
  workflow_dispatch:

# Permisos para GitHub Actions
permissions:
  contents: read

jobs:
  Pruebas:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js (para Angular y Jest)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Versión de Node.js recomendada
          cache: 'npm'       # Configura el caché para npm automáticamente

      # 3. Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm ci

      # 4. Instalar Ionic CLI globalmente
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      # 5. Ejecutar pruebas unitarias con Karma
      - name: Run Karma tests
        run: npm test || true

      # 6. Ejecutar pruebas E2E con Cypress
      - name: e2e cypress
        run: npx cypress run

  build:
    runs-on: ubuntu-latest
    needs: Pruebas # Este job se ejecutará solo si 'Pruebas' pasa exitosamente

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Limpiar node_modules y package-lock.json
      - name: Clean node_modules and package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      # 4. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 5. Instalar Ionic CLI globalmente
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      # 6. Construir la aplicación con Ionic
      - name: Build Ionic App
        run: ionic build

      # 7. Copiar archivos al proyecto Android
      - name: Copy to Android
        run: ionic cap copy

      # 8. Sincronizar archivos con Capacitor
      - name: Sync with Capacitor
        run: ionic cap sync
